package com.example.myapplication;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Admin_Principal_V extends VerticalLayout {
	protected ComboBox<diagrama_bd.base_de_datos.Servicio> boxO1;
	protected ComboBox<diagrama_bd.base_de_datos.Servicio> boxO2;
	protected ComboBox<diagrama_bd.base_de_datos.Servicio> boxO3;
	protected ComboBox<diagrama_bd.base_de_datos.Servicio> boxO4;
	protected ComboBox<diagrama_bd.base_de_datos.Servicio> boxO5;
	protected ComboBox<diagrama_bd.base_de_datos.Servicio> boxO6;
	protected Button btnGuardarCambios;

	public Admin_Principal_V() {
		Design.read(this);
	}
}
