package com.example.myapplication;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AdminServicios_V extends CssLayout {
	protected HorizontalLayout menuInterno;
	protected TabSheet menuMisDatos;
	protected VerticalLayout fijoFibraMobil;
	protected ComboBox<diagrama_bd.base_de_datos.Servicio> ofertasFFM;
	protected Button addOfertaFFM;
	protected TextField nombreFFM;
	protected TextField precioFFM;
	protected TextArea caracccicasFFM;
	protected Button btnModificarFFM;
	protected Button btnEliminarFFM;
	protected VerticalLayout tV;
	protected ComboBox<diagrama_bd.base_de_datos.Servicio> ofertasTV;
	protected Button addOfertaTV;
	protected TextField nombreTV;
	protected TextField precioTV;
	protected TextArea caracteristicasTV;
	protected Button btnModificarTV;
	protected Button btnEliminarTV;
	protected VerticalLayout combi;
	protected ComboBox<diagrama_bd.base_de_datos.Servicio> ofertasCombis;
	protected Button addOfertaCombi;
	protected TextField nombreCombi;
	protected TextField precioCombi;
	protected TextArea caracteristicasCombi;
	protected Button btnModificarCombi;
	protected Button btnEliminarCombi;
	protected AbsoluteLayout layoutNuevaOferta;

	public AdminServicios_V() {
		Design.read(this);
	}
}
