package com.example.myapplication;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DetalleComercial_V extends VerticalLayout {
	protected Label comercialNombre;
	protected Label comercialApellido1;
	protected Label comercialApellido2;
	protected Label comercialDomicilio;
	protected Label comercialEmail;
	protected Button btnModificarComercial;
	protected Button btnCerrarComercial;
	protected AbsoluteLayout layoutUpdateComercial;

	public DetalleComercial_V() {
		Design.read(this);
	}
}
