package com.example.myapplication;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MisFacturas_V extends CssLayout {
	protected HorizontalLayout menuInterno;
	protected TabSheet menuMisDatos;
	protected Label lblNfactura;
	protected Label lblServicio;
	protected Label lblFecha;
	protected Label lblImporte;
	protected VerticalLayout layoutTableFacturas;
	protected Grid<diagrama_bd.base_de_datos.Factura> tableFacturas;

	public MisFacturas_V() {
		Design.read(this);
	}
}
