package com.example.myapplication;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ModificarContrato_V extends CssLayout {
	protected ComboBox<java.lang.String> boxFijo;
	protected ComboBox<java.lang.String> boxFibra;
	protected ComboBox<java.lang.String> boxMovil;
	protected ComboBox<java.lang.String> boxTv;
	protected ComboBox<java.lang.String> boxCombi;

	public ModificarContrato_V() {
		Design.read(this);
	}
}
