package com.example.myapplication;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class NuevoCliente_V extends VerticalLayout {
	protected Label lblNombreTitulo;
	protected TextField nuevoClienteDNI;
	protected TextField nuevoClienteNombre;
	protected TextField nuevoClienteApellido1;
	protected TextField nuevoClienteApellido2;
	protected TextField nuevoClienteDomicilio;
	protected TextField nuevoClienteEmail;
	protected TextField nuevoClientePassword1;
	protected TextField nuevoClientePassword2;
	protected TextField nuevoClienteIBAN1;
	protected TextField nuevoClienteIBAN2;
	protected TextField nuevoClienteIBAN3;
	protected TextField nuevoClienteIBAN4;
	protected ComboBox<java.lang.String> listaServiciosCrearCliente;
	protected Button btn_;
	protected Button btnCancelar;
	protected Button guardarClienteEnBD;

	public NuevoCliente_V() {
		Design.read(this);
	}
}
