package com.example.myapplication;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class NuevoComercial_V extends VerticalLayout {
	protected Label tituloAddComercial;
	protected TextField nuevoComercialDNI;
	protected TextField nuevoComercialNombre;
	protected TextField nuevoComercialApellido1;
	protected TextField nuevoComercialApellido2;
	protected TextField nuevoComercialDomicilio;
	protected TextField nuevoComercialEmail;
	protected TextField nuevoComercialPassword1;
	protected TextField nuevoComercialPassword2;
	protected Button btnCancelar;
	protected Button guardarComercialEnBD;

	public NuevoComercial_V() {
		Design.read(this);
	}
}
